name: Conan create ros-kilted

on:
  pull_request:

jobs:
  conan-create:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            profile: profiles/windows-msvc
            conan_home: C:/.c2
          - runner: macos-latest
            profile: profiles/macos-clang
            conan_home: /tmp/conan-ci

    runs-on: ${{ matrix.runner }}
    env:
      CONAN_HOME: ${{ matrix.conan_home }}

    steps:
      - name: Enable long paths for git
        if: runner.os == 'Windows'
        run: git config --global core.longpaths true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Conan home
        shell: bash
        run: mkdir -p "$CONAN_HOME"

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2.2
        with:
          cmake-version: "3.31.0"

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          update-environment: false

      - name: Prepend Python to System PATH
        shell: bash
        run: echo "$(dirname '${{ steps.setup_python.outputs.python-path }}')" >> "$GITHUB_PATH"

      - name: Install latest Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan --version

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Add local recipes index
        working-directory: ${{ github.workspace }}
        run: conan remote add conan-ros-index . --type=local-recipes-index

      - name: Add artifactory Conan remote
        run: conan remote add conan-ros {{github.secrets.ARTIFACTORY_URL}}
        run: conan remote login -p {{github.secrets.ARTIFACTORY_PASSWORD}} {{github.secrets.ARTIFACTORY_USER}}

      - name: Build conan dependencies
        run: conan install --requires=ros-kilted/0.1.0 --build=~ros-kilted* --build=missing --profile=${{ matrix.profile }}

      - name: Upload conan dependencies
        run: conan upload "*" --all -r conan-ros

      - name: Conan create
        working-directory: ${{ github.workspace }}
        run: conan create recipes/ros-kilted/all --version=0.1.0 --build=missing --profile=${{ matrix.profile }}

      - name: Find and run examples
        shell: bash
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -u "${{ github.workspace }}/.github/run_ci_tests.py"
